### ISSUE TITLE
About the implementation of dads.

### ISSUE THREAD

**Issue by gaiyi114514** [Rooshy-yang/BeCL#1]
Thank you for your outstanding work!

I am new to the field of unsupervised reinforcement learning. What confused me is whether the reproduction of DADS in your work is based on DDPG to be consistent with [URLB](https://github.com/rll-research/url_benchmark), or based on SAC as done in [irm](https://github.com/ademiadeniji/irm). Is it possible to include your implementation of DADS and the 2D Maze environment in the code base?

Look forward to your reply!

**Comment by Rooshy-yang** [comment]
Thanks for your interest. DADS uses ppo as a basic RL algorithm in our maze as our maze environment builds on the top of the open-source code from the paper [[Explore, Discover and Learn: Unsupervised Discovery of State-Covering Skills](https://arxiv.org/abs/2002.03647)](https://arxiv.org/abs/2002.03647) and follows its default setting. You can easily replicate baselines based on it. We will update our repository after our code clean-up. :)

**Comment by gaiyi114514** [comment]
I get it! Thank you for your timely reply
