### ISSUE TITLE
About the results reported in the paper

### ISSUE THREAD

**Issue by yingchengyang** [Rooshy-yang/BeCL#3]
Thanks a lot for your wonderful work! I'm curious about the results the state-based DMC reported in Fig.5 of the paper. Are there raw numerical results of baselines an BeCL so that we can follow your results to draw similar figures? Thanks a lot!

**Comment by Rooshy-yang** [comment]
After completing the experiments, I mainly preserved the figures in papers and did not separately save the raw numerical data (in old cluster). However, the complete code has been provided, and you can use it to reproduce the experimental results. 

If you encounter any issues while reproducing the experimental results. Please don’t hesitate to let me know. I’ll do my best to assist you.

**Comment by yingchengyang** [comment]
Thanks a lot!
